/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import classe.Chargement;
import classe.Fonctions;
import db.DBAlliage;
import db.DBChargement;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author bunela
 */
public class Fenetre_principale extends javax.swing.JFrame {

    private int alliage = 0;
    private String type	= "";
    //private static ArrayList <LigneSaisieDechet> listeSaisieDechet; 
    /**
     * Creates new form Fenetre_principale
     */
    public Fenetre_principale() {
        initComponents();
        panel_feuille.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_identite = new javax.swing.JPanel();
        label_relais = new javax.swing.JLabel();
        label_nom1 = new javax.swing.JLabel();
        label_nom2 = new javax.swing.JLabel();
        label_alliage = new javax.swing.JLabel();
        label_typefour = new javax.swing.JLabel();
        label_pdb = new javax.swing.JLabel();
        typefour_value = new javax.swing.JComboBox();
        alliage_value = new javax.swing.JComboBox();
        relais_value = new javax.swing.JComboBox();
        nom1_value = new javax.swing.JTextField();
        nom2_value = new javax.swing.JTextField();
        pdb_value = new javax.swing.JTextField();
        bouton_annuler = new javax.swing.JButton();
        bouton_creerchargement = new javax.swing.JButton();
        panel_feuille = new javax.swing.JPanel();
        panel_ajoutcomposant = new javax.swing.JPanel();
        categorie_box = new javax.swing.JComboBox();
        type_box = new javax.swing.JComboBox();
        alliage_box = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        poids1_value = new javax.swing.JTextField();
        poids2_value = new javax.swing.JTextField();
        poids3_value = new javax.swing.JTextField();
        poids4_value = new javax.swing.JTextField();
        poids5_value = new javax.swing.JTextField();
        poids6_value = new javax.swing.JTextField();
        qte1_value = new javax.swing.JTextField();
        qte2_value = new javax.swing.JTextField();
        qte3_value = new javax.swing.JTextField();
        qte4_value = new javax.swing.JTextField();
        qte5_value = new javax.swing.JTextField();
        qte6_value = new javax.swing.JTextField();
        total1_text = new javax.swing.JLabel();
        total2_text = new javax.swing.JLabel();
        total3_text = new javax.swing.JLabel();
        total4_text = new javax.swing.JLabel();
        total5_text = new javax.swing.JLabel();
        total6_text = new javax.swing.JLabel();
        total_info = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ajout_info = new javax.swing.JLabel();
        type_info = new javax.swing.JLabel();
        alliage_info = new javax.swing.JLabel();
        alliage_mot = new javax.swing.JLabel();
        panel_auteur = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nom1_text = new javax.swing.JLabel();
        nom2_text = new javax.swing.JLabel();
        relais_text = new javax.swing.JLabel();
        idfournee_text = new javax.swing.JLabel();
        date_text = new javax.swing.JLabel();
        alliage_text = new javax.swing.JLabel();
        panel_pdb_precedent = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        poidspdb_text = new javax.swing.JLabel();
        idfourneepdb_text = new javax.swing.JLabel();
        alliagepdb_text1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau_pdb = new javax.swing.JTable();
        panel_addelem_compoconnue = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        panel_saisie_pion = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        panel_checklist = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panel_compochecklist = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        fichier = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        rechercher_menu = new javax.swing.JMenu();
        aide_menu = new javax.swing.JMenu();
        imprimer_menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        label_relais.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_relais.setText("Relais :");

        label_nom1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_nom1.setText("Nom1 :");

        label_nom2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_nom2.setText("Nom2 :");

        label_alliage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_alliage.setText("Alliage :");

        label_typefour.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_typefour.setText("Type de four :");

        label_pdb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_pdb.setText("Poids pieds de bain :");

        typefour_value.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Thermcon" , "Demag"}));

        alliage_value.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1050","1200","8011","8906","8979","8079","8666","8006" }));

        relais_value.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matin", "Après-midi", "Nuit" }));

        bouton_annuler.setText("Annuler");

        bouton_creerchargement.setText("Créer chargement");
        bouton_creerchargement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_creerchargementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_identiteLayout = new javax.swing.GroupLayout(panel_identite);
        panel_identite.setLayout(panel_identiteLayout);
        panel_identiteLayout.setHorizontalGroup(
            panel_identiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_identiteLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(panel_identiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_typefour)
                    .addComponent(label_alliage)
                    .addComponent(label_pdb)
                    .addComponent(label_nom1)
                    .addComponent(label_nom2)
                    .addComponent(label_relais))
                .addGap(29, 29, 29)
                .addGroup(panel_identiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nom2_value)
                    .addComponent(typefour_value, 0, 106, Short.MAX_VALUE)
                    .addComponent(nom1_value)
                    .addComponent(relais_value, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pdb_value)
                    .addComponent(alliage_value, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_identiteLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(bouton_creerchargement)
                .addGap(29, 29, 29)
                .addComponent(bouton_annuler)
                .addGap(78, 78, 78))
        );
        panel_identiteLayout.setVerticalGroup(
            panel_identiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_identiteLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel_identiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relais_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_relais))
                .addGap(18, 18, 18)
                .addGroup(panel_identiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom1_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nom1))
                .addGap(18, 18, 18)
                .addGroup(panel_identiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nom2)
                    .addComponent(nom2_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_identiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_alliage)
                    .addComponent(alliage_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_identiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typefour_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_typefour))
                .addGap(17, 17, 17)
                .addGroup(panel_identiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_pdb)
                    .addComponent(pdb_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panel_identiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton_annuler)
                    .addComponent(bouton_creerchargement))
                .addContainerGap())
        );

        panel_feuille.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_feuille.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_feuille.setMaximumSize(new java.awt.Dimension(1024, 768));
        panel_feuille.setMinimumSize(new java.awt.Dimension(1024, 768));
        panel_feuille.setName("Feuille four");

        categorie_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amma", "Lingot", "Déchet"}));
        categorie_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                categorie_boxItemStateChanged(evt);
            }
        });
        categorie_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorie_boxActionPerformed(evt);
            }
        });

        type_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        type_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_boxActionPerformed(evt);
            }
        });

        alliage_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        alliage_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alliage_boxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("1 - Catégorie :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("2 - Type :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Information sur l'ajout :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("3 - Ajout des poids et quantité");

        jLabel5.setText("poids   x    quantité");

        jLabel6.setText("x");

        jLabel8.setText("x");

        jLabel10.setText("x");

        jLabel12.setText("x");

        jLabel14.setText("x");

        jLabel37.setText("x");

        poids1_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poids1_valueActionPerformed(evt);
            }
        });

        poids2_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poids2_valueActionPerformed(evt);
            }
        });

        poids3_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poids3_valueActionPerformed(evt);
            }
        });

        poids4_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poids4_valueActionPerformed(evt);
            }
        });

        poids5_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poids5_valueActionPerformed(evt);
            }
        });

        poids6_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poids6_valueActionPerformed(evt);
            }
        });

        qte1_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qte1_valueActionPerformed(evt);
            }
        });

        qte2_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qte2_valueActionPerformed(evt);
            }
        });

        qte3_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qte3_valueActionPerformed(evt);
            }
        });

        qte4_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qte4_valueActionPerformed(evt);
            }
        });

        qte5_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qte5_valueActionPerformed(evt);
            }
        });

        qte6_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qte6_valueActionPerformed(evt);
            }
        });

        total1_text.setText("=");

        total2_text.setText("=");

        total3_text.setText("=");

        total4_text.setText("=");

        total5_text.setText("=");

        total6_text.setText("=");

        total_info.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        total_info.setText("- Total : 0 kg");

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ajout_info.setText("- Ajout :");

        type_info.setText("- Type :");

        alliage_info.setText("- Alliage :  -");

        alliage_mot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alliage_mot.setText("Alliage :");

        javax.swing.GroupLayout panel_ajoutcomposantLayout = new javax.swing.GroupLayout(panel_ajoutcomposant);
        panel_ajoutcomposant.setLayout(panel_ajoutcomposantLayout);
        panel_ajoutcomposantLayout.setHorizontalGroup(
            panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                        .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(alliage_mot)
                                        .addComponent(jLabel2)))
                                .addGap(18, 18, 18)
                                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(type_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(alliage_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(categorie_box, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(total_info)
                            .addComponent(ajout_info)
                            .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_ajoutcomposantLayout.createSequentialGroup()
                                    .addComponent(type_info)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(alliage_info))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                                    .addComponent(poids5_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(qte5_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(total5_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                                    .addComponent(poids4_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(qte4_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(total4_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                                    .addComponent(poids3_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(qte3_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(total3_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                                        .addComponent(poids2_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qte2_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(total2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                                        .addComponent(poids1_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qte1_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(total1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                                        .addComponent(poids6_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(qte6_value, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(total6_text, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel5)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ajoutcomposantLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(152, 152, 152))))
        );
        panel_ajoutcomposantLayout.setVerticalGroup(
            panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(categorie_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(type_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alliage_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alliage_mot))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ajout_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type_info)
                    .addComponent(alliage_info))
                .addGap(18, 18, 18)
                .addComponent(total_info)
                .addContainerGap())
            .addGroup(panel_ajoutcomposantLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qte1_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poids1_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(total1_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qte2_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poids2_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(total2_text))
                .addGap(8, 8, 8)
                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qte3_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poids3_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(total3_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qte4_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poids4_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(total4_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qte5_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poids5_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(total5_text))
                .addGap(6, 6, 6)
                .addGroup(panel_ajoutcomposantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qte6_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poids6_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total6_text)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 85, Short.MAX_VALUE))
        );

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Nom1 :");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Nom2 :");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Relais :");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Date :");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("ID fournée :");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Alliage :");

        javax.swing.GroupLayout panel_auteurLayout = new javax.swing.GroupLayout(panel_auteur);
        panel_auteur.setLayout(panel_auteurLayout);
        panel_auteurLayout.setHorizontalGroup(
            panel_auteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_auteurLayout.createSequentialGroup()
                .addGroup(panel_auteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_auteurLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nom2_text, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addGroup(panel_auteurLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nom1_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(32, 32, 32)
                .addGroup(panel_auteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_auteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_auteurLayout.createSequentialGroup()
                        .addComponent(idfournee_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panel_auteurLayout.createSequentialGroup()
                        .addComponent(relais_text, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(40, 40, 40)))
                .addGroup(panel_auteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(panel_auteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alliage_text, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(date_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_auteurLayout.setVerticalGroup(
            panel_auteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_auteurLayout.createSequentialGroup()
                .addGroup(panel_auteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_auteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27))
                    .addComponent(relais_text, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_auteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_auteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(jLabel28))
                    .addComponent(nom2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idfournee_text, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(panel_auteurLayout.createSequentialGroup()
                .addComponent(date_text, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alliage_text, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Caractéristiques du pied de bain précédent");

        jLabel31.setText("Poids :");

        jLabel32.setText("Alliage :");

        jLabel33.setText("ID fournée :");

        tableau_pdb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cu", "Mg", "Fe", "Mn", "Si", "Zn", "Ti", "PbCdHg"
            }
        ));
        tableau_pdb.setFocusable(false);
        tableau_pdb.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tableau_pdb);

        javax.swing.GroupLayout panel_pdb_precedentLayout = new javax.swing.GroupLayout(panel_pdb_precedent);
        panel_pdb_precedent.setLayout(panel_pdb_precedentLayout);
        panel_pdb_precedentLayout.setHorizontalGroup(
            panel_pdb_precedentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pdb_precedentLayout.createSequentialGroup()
                .addComponent(jLabel30)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_pdb_precedentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_pdb_precedentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pdb_precedentLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poidspdb_text, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addComponent(alliagepdb_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idfourneepdb_text, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(panel_pdb_precedentLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        panel_pdb_precedentLayout.setVerticalGroup(
            panel_pdb_precedentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pdb_precedentLayout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_pdb_precedentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(poidspdb_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idfourneepdb_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alliagepdb_text1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331))
        );

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Ajout d'un composant avec une composition connue :");

        jRadioButton1.setText("Ext Vert");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Ext Noir");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Sows");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Poids :");

        jButton2.setText("Ajouter");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cu", "Mg", "Fe", "Mn", "Si", "Zn", "Ti", "PbCdHg"
            }
        ));
        jTable2.setEnabled(false);
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout panel_addelem_compoconnueLayout = new javax.swing.GroupLayout(panel_addelem_compoconnue);
        panel_addelem_compoconnue.setLayout(panel_addelem_compoconnueLayout);
        panel_addelem_compoconnueLayout.setHorizontalGroup(
            panel_addelem_compoconnueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addelem_compoconnueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_addelem_compoconnueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_addelem_compoconnueLayout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jRadioButton3)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel35)
                        .addGap(88, 88, 88)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel34)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_addelem_compoconnueLayout.setVerticalGroup(
            panel_addelem_compoconnueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addelem_compoconnueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_addelem_compoconnueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_addelem_compoconnueLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_addelem_compoconnueLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_addelem_compoconnueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel35)
                            .addComponent(jButton2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pion1", null, null, null, null, null, null, null, null},
                {"Pion2", null, null, null, null, null, null, null, null},
                {"Pion3", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pion", "Cu", "Mg", "Fe", "Mn", "Si", "Zn", "Ti", "PbCdHg"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pion precedent", "Cu", "Mg", "Fe", "Mn", "Si", "Zn", "Ti", "PbCdHg"
            }
        ));
        jTable4.setEnabled(false);
        jScrollPane6.setViewportView(jTable4);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Saisie et consultation des pions :");

        jButton3.setText("Ajouter");

        javax.swing.GroupLayout panel_saisie_pionLayout = new javax.swing.GroupLayout(panel_saisie_pion);
        panel_saisie_pion.setLayout(panel_saisie_pionLayout);
        panel_saisie_pionLayout.setHorizontalGroup(
            panel_saisie_pionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_saisie_pionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_saisie_pionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(panel_saisie_pionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_saisie_pionLayout.setVerticalGroup(
            panel_saisie_pionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_saisie_pionLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Check-list contenant les charges du four :");

        javax.swing.GroupLayout panel_checklistLayout = new javax.swing.GroupLayout(panel_checklist);
        panel_checklist.setLayout(panel_checklistLayout);
        panel_checklistLayout.setHorizontalGroup(
            panel_checklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_checklistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        panel_checklistLayout.setVerticalGroup(
            panel_checklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_checklistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Validé", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "V", "Cu", "Mg", "Fe", "Mn", "Si", "Zn", "Ti", "PbCdHg"
            }
        ));
        jTable5.setEnabled(false);
        jScrollPane7.setViewportView(jTable5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"En cours", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "?", "Cu", "Mg", "Fe", "Mn", "Si", "Zn", "Ti", "PbCdHg"
            }
        ));
        jTable6.setEnabled(false);
        jScrollPane8.setViewportView(jTable6);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Composition en cours de la check-list");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Composition validée de la check-list");

        javax.swing.GroupLayout panel_compochecklistLayout = new javax.swing.GroupLayout(panel_compochecklist);
        panel_compochecklist.setLayout(panel_compochecklistLayout);
        panel_compochecklistLayout.setHorizontalGroup(
            panel_compochecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_compochecklistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_compochecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_compochecklistLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_compochecklistLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(276, 276, 276))
                    .addGroup(panel_compochecklistLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7)))
        );
        panel_compochecklistLayout.setVerticalGroup(
            panel_compochecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_compochecklistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_feuilleLayout = new javax.swing.GroupLayout(panel_feuille);
        panel_feuille.setLayout(panel_feuilleLayout);
        panel_feuilleLayout.setHorizontalGroup(
            panel_feuilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_feuilleLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panel_feuilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_addelem_compoconnue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_ajoutcomposant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_saisie_pion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(panel_feuilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_auteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_checklist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_pdb_precedent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_compochecklist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panel_feuilleLayout.setVerticalGroup(
            panel_feuilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_feuilleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_feuilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_feuilleLayout.createSequentialGroup()
                        .addComponent(panel_ajoutcomposant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(panel_addelem_compoconnue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(panel_saisie_pion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_feuilleLayout.createSequentialGroup()
                        .addComponent(panel_auteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(panel_pdb_precedent, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_checklist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(panel_compochecklist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fichier.setText("Fichier");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Nouveau chargement");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fichier.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Ouvrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        fichier.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Enregistrer");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        fichier.add(jMenuItem3);

        menu.add(fichier);

        rechercher_menu.setText("Rechercher");
        menu.add(rechercher_menu);

        aide_menu.setText("Aide");
        menu.add(aide_menu);

        imprimer_menu.setText("Imprimer");
        menu.add(imprimer_menu);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(panel_identite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_feuille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_feuille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_identite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void relais_value2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relais_value2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relais_value2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public boolean saisieFormulaireOk ( String []tab )
    {
        boolean formOk = true;

        for ( int i = 0 ; i < tab.length ; i++)
        {
                if ( tab[i].equals(""))
                        formOk = false;
        }
        return formOk;
    }
    
    private void bouton_creerchargementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_creerchargementActionPerformed

        String tabInfo[] = new String[6];
        int typeFour;
        int reponse = 2;
           
    // On stock le formulaire dans un tableau qu'on enverra a la feuilleFour 
        tabInfo[0] 	= nom1_value.getText();
        tabInfo[1] 	= nom2_value.getText();
        tabInfo[2] 	= pdb_value.getText();
        tabInfo[3] 	= relais_value.getSelectedItem().toString();
        tabInfo[4] 	= alliage_value.getSelectedItem().toString();
        tabInfo[5]	= typefour_value.getSelectedItem().toString();

        if ( tabInfo[5].equals("Thermcon"))     typeFour = 1;

        else                                    typeFour = 0;

        reponse = JOptionPane.showConfirmDialog(null, "Voulez vous créer ce nouveau chargement", "Confirmation de la création", JOptionPane.YES_NO_CANCEL_OPTION);	

        int idAlliage = 0 ;

        // Si le formulaire et correct et qu'on a validé
        // On envoie le tableau de saisie a la feuille principale pour créer le chargement
        if ( reponse == 0 )
        {
            if ( ! saisieFormulaireOk( tabInfo ) ) 
                        JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs pour créer le chargement", "Erreur de saisie", JOptionPane.ERROR_MESSAGE); 	

            else
            {
                if ( ! Fonctions.isInteger(tabInfo[2]))
                {
                        JOptionPane.showMessageDialog(null, "Le pied de bain ne doit comporter que les chiffres", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    try 
                    {
                        DBAlliage DBAlliage = new DBAlliage();
                        idAlliage = DBAlliage.getIdAlliage(Integer.parseInt(tabInfo[4])); // On recupere l'id de l'alliage en fonction de la saisie

                    DBChargement DB = null;
                    int num = 0;

                     try 
                     {
                             DB = new DBChargement();
                     } 
                     catch (ClassNotFoundException e1) 
                     {
                             e1.printStackTrace();
                     } 
                     catch (SQLException e1) 
                     {
                             e1.printStackTrace();
                     }	

                     try 
                     {
                             num = DB.getNumeroDernierChargement();
                     } 
                     catch (SQLException e2) 
                     {
                         e2.printStackTrace();
                     }
                     Chargement chargementCreate = new Chargement( num+1 , typeFour, tabInfo[3], tabInfo[0], tabInfo[1], idAlliage , Integer.parseInt(tabInfo[2]) );
                    
                    Date maDateAvecFormat=new Date();
                    SimpleDateFormat dateStandard = new SimpleDateFormat("dd/MM/yyyy");
                    String dateDuJour = dateStandard.format(maDateAvecFormat);
                    date_text.setText(dateDuJour );
                    idfournee_text.setText(chargementCreate.getIdChargement() + "");
                    nom1_text.setText(tabInfo[0]);
                    nom2_text.setText(tabInfo[1]);
                    relais_text.setText(tabInfo[3]);
                    alliage_text.setText(DBAlliage.getNomAlliage( chargementCreate.getIdAlliage())+"");
                            
                    poidspdb_text.setText(chargementCreate.getPoids_pdb_precedent() + "  kg");
                    idfourneepdb_text.setText((chargementCreate.getIdChargement() -1) + "");
                    alliagepdb_text1.setText(DBAlliage.getAlliageChargementPrecedent(chargementCreate) +"");
                    
                    
                    alliage_box.setVisible(false);
                    alliage_mot.setVisible(false);
                     try 
                     {
                             DB.insertChargement(chargementCreate);
                     } 
                     catch (SQLException e1) 
                     {
                             e1.printStackTrace();
                     }

                     panel_identite.setVisible(false);
                     remove(panel_identite);
                     panel_feuille.setVisible(true);

                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Fenetre_principale.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(Fenetre_principale.class.getName()).log(Level.SEVERE, null, ex);
                    }
                 }            
             }                        
         }		
    }//GEN-LAST:event_bouton_creerchargementActionPerformed

    private void categorie_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorie_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorie_boxActionPerformed

    public boolean aUnAlliage()
    {	
        return alliage != 0;
    }
    
    public String getType()
    {
        return this.type;
    }

    public int getAlliage()
    {
        return this.alliage;
    }
        
    private void type_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_boxActionPerformed
       //total_info.setText("- Total : " + getResultatListe() + " kg");

        total_info.setText("- Total :  kg");
        String type="";
        
        if (evt.getSource().equals(type_box) )
        {
            try {
                type = type_box.getSelectedItem().toString();	
            }
            catch (Exception y) 
            {
            }
        }
        type_info.setText("Type : " + type );
        total_info.setText("Total : 0 kg");
    }//GEN-LAST:event_type_boxActionPerformed

    private void qte2_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qte2_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qte2_valueActionPerformed

    private void poids2_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poids2_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poids2_valueActionPerformed

    private void poids3_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poids3_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poids3_valueActionPerformed

    private void qte3_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qte3_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qte3_valueActionPerformed

    private void poids4_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poids4_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poids4_valueActionPerformed

    private void qte4_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qte4_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qte4_valueActionPerformed

    private void poids5_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poids5_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poids5_valueActionPerformed

    private void qte5_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qte5_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qte5_valueActionPerformed

    private void poids6_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poids6_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poids6_valueActionPerformed

    private void qte6_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qte6_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qte6_valueActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void poids1_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poids1_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poids1_valueActionPerformed

    private void qte1_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qte1_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qte1_valueActionPerformed
    
    /*public void majPoids(Chargement chargementCreate)
    {
        total_info.setText("Total : " + getResultatListe() + " kg");
    }
    
     public static int getResultatListe()
    {
        int resultat = 0;

       for ( int i = 0 ; i < listeSaisieDechet.size() ; i++ )
        {
                resultat += listeSaisieDechet.get(i).getResultat();
        }
        return resultat;
    }*/
    
    public void viderlisteSelection ( JComboBox selectionType)
    {
        DefaultComboBoxModel modele = (DefaultComboBoxModel)selectionType.getModel();
        modele.removeAllElements();
    }
    private void categorie_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_categorie_boxItemStateChanged
        String categorie = "";
        String type = "";
         String s = (String) (evt.getItem());
         
        int alliage = 0;
       
        String[] tabAmma    = { "Si", "As50", "AFe80", "AMn85", "Zn", "Cu"} ;
        String[] tabLingot  = { "16kg" , "T" } ;
        String[] tabDechet  = {"ExtVert","ExtNoir","bobinot3C","rives3C","compacteJaune","compacteVert", "compacteRouge","compacteBleu","compacteViolet","compacteBlanc","rivesDm","bobineATremper","Q190" };
	
        int[] tabAlliage = { 1050, 8011 ,8906 ,8979 ,8079 ,8666 ,8006 ,1200 ,3003 ,3903, 3904};
        
        
        if (  s.equals("Lingot") )
        {
            alliage_box.setVisible(false);
            alliage_mot.setVisible(false);
            ajout_info.setText("- Ajout : Lingot");
            
            viderlisteSelection(type_box);
            
            for ( int i = 0 ; i < tabLingot.length ; i++)		
                type_box.addItem(tabLingot[i]); 
            
            type = type_box.getSelectedItem().toString() ;
            type_info.setText( "- Type : " + type);
            
                alliage_info.setText( "- Alliage : -");
        }
		 
        if (  s.equals("Amma") )
        {	
            alliage_box.setVisible(false);
            alliage_mot.setVisible(false);
            ajout_info.setText("- Ajout : Amma");
            
            viderlisteSelection(type_box);
            
            for ( int i = 0 ; i < tabAmma.length ; i++)	 	
                type_box.addItem(tabAmma[i]);
            
            type = type_box.getSelectedItem().toString() ;
            type_info.setText( "- Type : " + type);
            alliage_info.setText( "- Alliage : -");
        }
		 
        if (  s.equals("Déchet") )
        {
            viderlisteSelection(type_box);
            viderlisteSelection(alliage_value);
            
            alliage_value.setVisible(true);
            ajout_info.setText("- Ajout : Déchet");
             
            for ( int i = 0 ; i < tabDechet.length ; i++)		
                type_box.addItem(tabDechet[i]);

            for ( int i = 0 ; i < tabAlliage.length ; i++) 	
                alliage_box.addItem ( tabAlliage[i]);
            
            type = type_box.getSelectedItem().toString() ;
            type_info.setText( "- Type : " + type);
            
            alliage = Integer.parseInt( alliage_box.getSelectedItem().toString() );
            alliage_info.setText( "- Alliage : "+ alliage);
            alliage_box.setVisible(true); 
            alliage_mot.setVisible(true);
        }
        
    }//GEN-LAST:event_categorie_boxItemStateChanged

    private void alliage_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alliage_boxActionPerformed
                
        if (evt.getSource().equals(alliage_box) )
        {	
            try {
                 alliage = Integer.parseInt(alliage_box.getSelectedItem().toString());	
            }
           catch (Exception y) 
            {
            }
        }
        
        if ( alliage != 0) 
     
            alliage_info.setText("- Alliage : " + alliage);
   
    }//GEN-LAST:event_alliage_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Fenetre_principale().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aide_menu;
    private javax.swing.JLabel ajout_info;
    private javax.swing.JComboBox alliage_box;
    private javax.swing.JLabel alliage_info;
    private javax.swing.JLabel alliage_mot;
    private javax.swing.JLabel alliage_text;
    private javax.swing.JComboBox alliage_value;
    private javax.swing.JLabel alliagepdb_text1;
    private javax.swing.JButton bouton_annuler;
    private javax.swing.JButton bouton_creerchargement;
    private javax.swing.JComboBox categorie_box;
    private javax.swing.JLabel date_text;
    private javax.swing.JMenu fichier;
    private javax.swing.JLabel idfournee_text;
    private javax.swing.JLabel idfourneepdb_text;
    private javax.swing.JMenu imprimer_menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JLabel label_alliage;
    private javax.swing.JLabel label_nom1;
    private javax.swing.JLabel label_nom2;
    private javax.swing.JLabel label_pdb;
    private javax.swing.JLabel label_relais;
    private javax.swing.JLabel label_typefour;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel nom1_text;
    private javax.swing.JTextField nom1_value;
    private javax.swing.JLabel nom2_text;
    private javax.swing.JTextField nom2_value;
    private javax.swing.JPanel panel_addelem_compoconnue;
    private javax.swing.JPanel panel_ajoutcomposant;
    private javax.swing.JPanel panel_auteur;
    private javax.swing.JPanel panel_checklist;
    private javax.swing.JPanel panel_compochecklist;
    private javax.swing.JPanel panel_feuille;
    private javax.swing.JPanel panel_identite;
    private javax.swing.JPanel panel_pdb_precedent;
    private javax.swing.JPanel panel_saisie_pion;
    private javax.swing.JTextField pdb_value;
    private javax.swing.JTextField poids1_value;
    private javax.swing.JTextField poids2_value;
    private javax.swing.JTextField poids3_value;
    private javax.swing.JTextField poids4_value;
    private javax.swing.JTextField poids5_value;
    private javax.swing.JTextField poids6_value;
    private javax.swing.JLabel poidspdb_text;
    private javax.swing.JTextField qte1_value;
    private javax.swing.JTextField qte2_value;
    private javax.swing.JTextField qte3_value;
    private javax.swing.JTextField qte4_value;
    private javax.swing.JTextField qte5_value;
    private javax.swing.JTextField qte6_value;
    private javax.swing.JMenu rechercher_menu;
    private javax.swing.JLabel relais_text;
    private javax.swing.JComboBox relais_value;
    private javax.swing.JTable tableau_pdb;
    private javax.swing.JLabel total1_text;
    private javax.swing.JLabel total2_text;
    private javax.swing.JLabel total3_text;
    private javax.swing.JLabel total4_text;
    private javax.swing.JLabel total5_text;
    private javax.swing.JLabel total6_text;
    private javax.swing.JLabel total_info;
    private javax.swing.JComboBox type_box;
    private javax.swing.JLabel type_info;
    private javax.swing.JComboBox typefour_value;
    // End of variables declaration//GEN-END:variables
}
